POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Igor Joao",
  "username": "lamas100"
}
###
GET http://localhost:3333/users/8275faac-1ec1-42c1-9654-8e8b4ebc22ea
Content-Type: application/json

###
POST http://localhost:3333/todos
Content-Type: application/json
username: lamas250

{
  "title": "56432342",
  "deadline": "2020-10-10"
}
###
PUT http://localhost:3333/todos/d4b71f0b-9180-498e-840e-0d12149764e6
Content-Type: application/json
username: lamas250

{
  "title": "Editado checksEcistidsTODO OK",
  "deadline": "2020-10-10"
}